basic/models/Good.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * TODO: добавить кол-во просмотров.
 * TODO: выбор полей для превью
 * This is the model class for table "good".
 *
 * @property integer $id
 * @property integer $image_id
 * @property string $name
 * @property integer $category_id
 * @property string $about
 * @property string $updated
 * @property string $created
 * @property string $active
 * @property string $counter
 * @property array $items
 *
 * @property Category $category
 * @property Image $image
 * @property GoodImage[] $goodImages
 * @property Image[] $images
 * @property GoodLabel[] $goodLabels
 * @property Label[] $labels
 * @property Value[] $values
 */
class Good extends \yii\db\ActiveRecord
{
    private $items;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'good';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['image_id', 'category_id', 'counter', 'active'], 'integer'],
            [['name', 'category_id'], 'required'],
            [['about'], 'string'],
            [['updated', 'created'], 'safe'],
            [['name'], 'string', 'max' => 150]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'image_id' => 'Главное изображение',
            'counter' => 'Щётчик',
            'active' => 'Активность',
            'name' => 'Имя',
            'category_id' => 'Категория',
            'about' => 'Пояснение',
            'updated' => 'Обновлено',
            'created' => 'Созданно',
        ];
    }

    public function attributeLabel($name)
    {
//        return $this->getAttributeLabel()
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImage()
    {
        return $this->hasOne(Image::className(), ['id' => 'image_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGoodImages()
    {
        return $this->hasMany(GoodImage::className(), ['good_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getImages()
    {
        return $this->hasMany(Image::className(), ['id' => 'image_id'])->viaTable('good_image', ['good_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGoodLabels()
    {
        return $this->hasMany(GoodLabel::className(), ['good_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLabels()
    {
        return $this->hasMany(Label::className(), ['id' => 'label_id'])->viaTable('good_label', ['good_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getValues()
    {
        return $this->hasMany(Value::className(), ['id' => 'value_id'])->viaTable('good_value', ['good_id' => 'id']);
    }

    /**
     * Возвращает обьекты для клиентской части
     * @param array $where
     * @param array $with
     * @return array|\yii\db\ActiveRecord[]
     */
    static public function findAllByClient(array $where, array $with = [], $count = null)
    {
        $query =  self::find()
            ->where($where)
            ->joinWith(['category'])
            ->andWhere(['good.active' => '1', 'category.active' => 1]);

        foreach ($with as $relation) {
            $query->with($relation);
        }

        if ($count) $query->limit($count);
        return $query->all();
    }

    /**
     * Возвращает обьект для клиентской части
     * @param array $where
     * @param array $with
     * @return array|null|\yii\db\ActiveRecord
     */
    static public function findOneByClient(array $where, array $with = [])
    {
        $query =  self::find()
            ->where($where)
            ->joinWith(['category'])
            ->andWhere(['good.active' => '1', 'category.active' => 1]);

        foreach ($with as $relation) {
            $query->with($relation);
        }
        return $query->one();
    }
    
    public function getItems()
    {
        return $this->items;
    }
    
    /**
     * @return array
     */
    public function initFieldValue () {
        $this->items = $this->category->getItemsToUpdate(['good_id' => $this->id]);
        
        foreach ($this->items as $key1 => $value) {
            if (!Model::loadMultiple($this->items[$key1], Yii::$app->request->post(), $key1)) {
                return false;   
            }
        }
        return true;
    }
}

basic/controllers/GoodController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Good;
use app\modules\admin\models\GoodSearch;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class GoodController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays a single Good model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * @param int $page
     * @param null $category_id
     * @return string
     */
    public function actionSearch($page = 1, $category_id = null)
    {
        $limit = 9;
        $searchModel = new GoodSearch();
        $count = $searchModel->search(Yii::$app->request->queryParams, $category_id)->query->limit($limit)->offset($limit* ($page - 1))->count();
        $countPage = ceil($count / $limit);
        $models = $searchModel->search(Yii::$app->request->queryParams, $category_id)->query->limit($limit)->offset($limit* ($page - 1))->all();

        $category = $category_id ? Category::findOne($category_id) : null;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'models' => $models,
            'countPage' => $countPage,
            'page' => $page,
            'category' => $category
        ]);
    }

    /**
     * Finds the Good model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Good the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Good::findOneByClient(['good.id' => $id], ['values', 'values.field', 'category', 'image'])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/views/good/_preview_good.php
<?php

/* @var $good \app\models\Good */

?>
<div class="col-sm-6 col-md-4 col-fixed ">
    <div class="thumbnail">
        <a href="<?= \yii\helpers\Url::to(['/good/view', 'id' => $good->id]) ?>">
            <h4><?= $good->name ?></h4>
            <img class="preview-image-good" src="<?= $good->image->image ?>" alt="<?= $good->name ?>" data-src="holder.js/300x200">
        </a>
        <div class="caption">
            <p>
                <label>Категория: </label>
                <a href="<?= \yii\helpers\Url::toRoute(["good/search", 'page' => 1, "category_id" => $good->category_id]) ?>"><?= $good->category->name ?></a>
            </p>
            <?php foreach ($good->values as $value) { ?>
                <?php if ($value->field->preview) { ?>
                    <p>
                        <label><?= $value->field->name ?></label>: <?= $value->value ?>
                    </p>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</div>

basic/views/good/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\GoodSearch */
/* @var $category \app\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="good-search well bs-component">
    <div class="row">
        <?php $form = ActiveForm::begin([
            'action' => ['search', 'page' => 1, 'category_id' => $category ? $category->id : null],
            'method' => 'get',
        ]); ?>
        <div class="col-sm-2">
            <legend>Поиск:</legend>
        </div>
        <div class="col-sm-8">
            <?= $form->field($model, 'name', ['template' => '{input}']) ?>
        </div>

        <div class="col-sm-2 form-group">
            <?= Html::submitButton('Искать', ['class' => 'btn btn-primary']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

basic/views/good/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use \app\models\Category;

/* @var $this yii\web\View */
/* @var $models array */
/* @var $category Category */
/* @var $countPage integer */
/* @var $searchModel app\modules\admin\models\GoodSearch */


$this->title = $category ? $category->name : "Товары";
$this->params['breadcrumbs'][] = $this->title;

$dict = [
    'category_view' => Category::getList(['view' => true]),
    'category' => Category::getList(),
];

?>
<div class="good-index">
    <?php if ($category) { ?>
        <h2>Категория: "<?= $category->name ?>"</h2>
    <?php } ?>

    <?php  echo $this->render('_search', ['model' => $searchModel, "dict" => $dict, 'category' => $category]); ?>

    <div class="site-index">
        <div class="row">
            <?php if (!empty($models)) {
                foreach ($models as $good) { ?>
                    <?= $this->render('../good/_preview_good', ["good" => $good]) ?>
                <?php }
            } else { ?>
                <div class="col-sm-12">
                    <h4>К сожалению по вашему запросу, совпадений не обнаружено.</h4>
                </div>
            <?php } ?>
        </div>
    </div>
    <nav>
        <ul class="pagination">
            <?php if (!($page == 1)) { ?>
                <li>
                    <a href="/good/search?page=<?= $page-1  ?>" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            <?php } ?>
            <?php for ($i = 1; $i <= $countPage; $i++) { ?>
                <?php if ($i == $page) { ?>
                    <li class="active"><a href="/good/search?page=<?= $i ?>"><?= $i ?></a></li>
                <?php } else { ?>
                    <li><a href="/good/search?page=<?= $i ?>"><?= $i ?></a></li>
                <?php } ?>
            <?php } ?>
            <?php if (!($page == $countPage)) { ?>
                <li>
                    <a href="/good/search?page=<?= $page+1 ?>" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            <?php } ?>
        </ul>
    </nav>
</div>

basic/views/good/view.php
<?php
/* @var $model \app\models\Good */
?>

<div class="view-div-good">
    <h4><?= $model->name ?></h4>
    <div class="row">
        <div class="col-md-12">
            <a style="float:left; margin: 7px 7px 7px 0;" href="<?= $model->image->image ?>" class="c-lightbox">
                <img src="<?= $model->image->image ?>" alt="<?= $model->name ?>" class="img-thumbnail preview-image-good">
            </a>
            <p>
                <label>Категория: </label>
                <a href="#"><?= $model->category->name ?></a>
            </p>
            <?php foreach ($model->values as $value) { ?>
                <p>
                    <label><?= $value->field->name ?></label>: <?= $value->value ?>
                </p>
            <?php } ?>
            <p><?= $model->about ?></p>
        </div>
    </div>
    <div class="row">
        <?php foreach ($model->images as $key => $image) { ?>
        <div class="col-sm-6 col-md-4 col-fixed-image">
            <a data-toggle="lightbox" href="<?= $image->image ?>" class="c-lightbox img-thumbnail">
                <div class="thumbnail">
                    <img class="preview-image-good"  src="<?= $image->image ?>" >
                </div>
            </a>
        </div>

        <?php } ?>
    </div>
</div>