basic/modules/admin/models/GoodForm.php
<?php

namespace app\modules\admin\models;

use app\models\Good;
use app\models\GoodValue;
use app\models\Image;
use app\models\Value;
use Yii;
use yii\base\Model;
use yii\web\UploadedFile;

class GoodForm extends Good
{

    private $items = [];
    
    /**
     * @var UploadedFile
     */
    public $file;
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['file'], 'file', 'maxSize' => 40000000, /*'extensions'=>'jpg, jpeg, gif, png'*/],
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        if (!$this->validate()) return false;
        if (!parent::save($runValidation, $attributeNames = null)) return false;

        foreach ($this->items['GoodValue'] as $value) {
            /** @var GoodValue  $value */
            $value->good_id = $this->id;
            if (!$value->save()) {
            }
        }
        if (!empty($this->items['Value'])) {
            foreach ($this->items['Value'] as $value) {
                /** @var Value  $value */
                if ($value->id && $value->save()) {
                } elseif (!$value->id && $value->save() && !$this->link('values', $value)) {
                }
            }
        }

        if ($this->file) {
            $fileName = (string)microtime(true).rand(0,1000). '.' . $this->file->extension;
            $path = '/image/' . $fileName;
            if ($this->file->saveAs(Yii::getAlias('@webroot'.$path))) {
                if ($this->image) {
                    $absPass = Yii::getAlias("@webroot".$this->image->image);
                    if (is_file($absPass)) unlink($absPass);
                    $this->image->name = $fileName;
                    $this->image->image = $path;
                    $this->image->save();
                } else {
                    $image = new Image();
                    $image->name = $fileName;
                    $image->image = $path;
                    $image->save();
                    $this->image_id = $image->id;
                    $this->save();
                }
                return true;
            } else {
                return false;
            }   
        }
        return true;
    }

    public function getIsNewRecord() {
        return empty($this->id);
    }

    public function getItems()
    {
        return $this->items;
    }

    public function load($data, $formName = null) {

        $scope = $formName === null ? $this->formName() : $formName;
        if (isset($data[$scope])) {
            $this->setAttributes($data[$scope], false);
        }
        
        $this->file = UploadedFile::getInstance($this, 'file');

        $this->items = $this->category->getItemsToUpdate(['good_id' => $this->id]);

        foreach ($this->items as $key1 => $value) {
            if (!Model::loadMultiple($this->items[$key1], Yii::$app->request->post(), $key1)) {
                return false;
            }
        }
        return true;
    }
}

basic/modules/admin/controllers/CategoryController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Category;
use app\modules\admin\models\CategoryTypeSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CategoryTypeSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update','id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->render('update', [
                'model' => $model,
            ]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->unlinkAll("fields", true);
        //TODO: Удалят вещи и значения полей
        $model->unlinkAll("labels", true);
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/modules/admin/views/category/_categoryForm.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
use \app\models\Category;
?>

<div class="category-form">
    <?php $form = ActiveForm::begin(); ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить категорию' : 'Обновить категорию', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?php if (!$model->isNewRecord) { ?>
            <?= Html::a('Удалить категорию', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => "Удалить категорию {$model->name}?",
                    'method' => 'post',
                ],
            ]) ?>
        <?php } ?>
    </div>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'parent_id')->dropDownList(Category::getParentList(),['prompt'=>'']) ?>
        </div>
        <?php if (!$model->isNewRecord) { ?>
            <div class="col-md-3">
                <?= $form->field($model, 'updated')->textInput(['readonly' => true]) ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'created')->textInput(['readonly' => true]) ?>
            </div>
        <?php } ?>
        <div class="col-md-10">
            <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
    <div class="<?= $model->isNewRecord ? 'hidden' : ''?>">
        <?php Pjax::begin(['enablePushState' => false]); ?>
        <?= $this->render('_field', ['model' => $model]) ?>
        <?php Pjax::end(); ?>
    </div>
</div>

basic/modules/admin/views/category/_field.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use \app\models\FieldType;
use \app\models\Field;;

/* @var $model app\models\Category */
/* @var $this yii\web\View */

$fieldTemplate = new Field();
//
//foreach ($model->labels as $label) {
//    $labelsToJs[] = "{
//        name: '{$label->name}',
//        id: '{$label->id}'
//    }";
//}
//
//foreach ($model->fields as $field) {
//    $fieldsToJs[] = "{
//        name: '{$field->name}',
//        id: '{$field->id}',
//        required: '{$field->required}',
//        dictionary: '{$field->dictionary}',
//        about: '{$field->about}',
//        type_id: '{$field->type_id}',
//    }";
//}
//
//$this->registerJs("data_fields = [".join(',',$fieldsToJs)."]; category_id = {$model->id};"."data_labels = [".join(',',$labelsToJs)."];",yii\web\View::POS_BEGIN);
?>
<div id="category-fields"></div>

<script type="text/template" id="category-fields-template">
    <h4><strong>Дополнительные поля</strong></h4>
    <?php $form = ActiveForm::begin([
        'action' => Url::toRoute(['/admin/field/update', 'categoryId' => $model->id]),
        'id' => 'fieldsUpdateForm'
    ]); ?>
        <?= Html::a('Добавить поле', 'javascript:void(0)', [
            'class' => 'btn btn-success',
            "id" => 'add-field',
        ]) ?>

        <table class="table">
            <tr>
                <td style="width: 485px">
                    <strong>Название</strong>
                </td>
                <td style="width: 100px">
                    <strong>Тип</strong>
                </td>
                <td style="width: 75px">
                    <strong>Словарь</strong>
                </td>
                <td style="width: 75px">
                    <strong>Обязательно</strong>
                </td>
                <td style="width: 75px">
                    <strong>Превью</strong>
                </td>
            </tr>
        </table>
        <div id="fields-table"></div>
    <?php ActiveForm::end(); ?>
</script>

<script type="text/template" id="field-form-template">
    <?php $form = ActiveForm::begin([
        'action' => 'save-field',
    ]); ?>
    <input type="hidden" id="field-<%= id %>-id" class="form-control" name="Field[<%= id %>][id]" value="<%= id %>">
        <tr>
            <td class="" style="width: 430px">
                <div class="form-group field-field-<%= id %>-name">
                    <input type="text" id="field-<%= id %>-name" class="form-control" name="Field[<%= id %>][name]" value="<%= name %>" placeholder="Введите название поля">
                </div>
            </td>
            <td style="width: 100px">
                <div class="form-group field-field-<%= id %>-type_id required">
                    <select id="field-<%= id %>-type_id" class="form-control" name="Field[<%= id %>][type_id]">
                        <?php foreach (FieldType::getList() as $id => $type) { ?>
                            <option  <% if (type_id == <?= $id ?>) { %>selected <% } %> value="<?= $id ?>"><?= $type ?></option>
                        <?php } ?>
                    </select>
                </div>
            </td>
            <td style="width: 75px">
                <div class="form-group field-field-<%= id %>-dictionary">
                    <select id="field-<%= id %>-dictionary" class="form-control" name="Field[<%= id %>][dictionary]">
                        <option value="1" <% if (dictionary == 1) { %>selected <% } %>>Да</option>
                        <option value="0" <% if (dictionary == 0) { %>selected <% } %>>Нет</option>
                    </select>
                </div>
            </td>
            <td style="width: 75px">
                <div class="form-group field-field-<%= id %>-required">
                    <select id="field-<%= id %>-required" class="form-control" name="Field[<%= id %>][required]">
                        <option <% if (required == 1) { %>selected <% } %> value="1">Да</option>
                        <option <% if (required == 0) { %>selected <% } %> value="0">Нет</option>
                    </select>
                </div>
            </td>
            <td style="width: 75px">
                <div class="form-group field-field-<%= id %>-preview">
                    <select id="field-<%= id %>-preview" class="form-control" name="Field[<%= id %>][preview]">
                        <option <% if (preview == 1) { %>selected <% } %> value="1">Да</option>
                        <option <% if (preview == 0) { %>selected <% } %> value="0">Нет</option>
                    </select>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <div class="form-group field-field-<%= id %>-about">
                    <input type="text" id="field-<%= id %>-about" class="form-control" name="Field[<%= id %>][about]" value="<%= about %>" placeholder="Введите пояснение к полю">
                </div>
            </td>
            <td>
                <a class="btn btn-sm btn-success" href="javascript:void(0)" id="save-field"><span class="glyphicon glyphicon-floppy-disk"></span></a>
                <a class="btn btn-sm btn-danger" href="javascript:void(0)" id="drop-field"><span class="glyphicon glyphicon-trash"></span></a>
                <!--
                <?= Html::a('<span class="glyphicon glyphicon-trash"></span>', 'javascript:void(0)', [
                    'class' => 'btn btn-sm btn-danger',
                    'data' => [
                        'confirm' => "Удалить поле?",
                        'method' => 'post',
                    ],
                ]) ?>
                -->
            </td>
        </tr>
    <?php ActiveForm::end(); ?>
</script>

<?php $this->registerJsFile('js/app/views/admin/category/fields.js', ['depends' => ['app\modules\admin\AppAsset',]]); ?>

basic/modules/admin/views/category/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use \app\models\Category;

/* @var $this yii\web\View */
/* @var $model app\models\Category */
/* @var $form yii\widgets\ActiveForm */

$this->registerJsFile('js/app/views/admin/category/form.js', ['depends' => ['app\modules\admin\AppAsset',]]);
?>
<script type="text/template" id="category-form-template">
    <div class="category-form well bs-component">
        <?php $form = ActiveForm::begin(); ?>
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? 'Добавить категорию' : 'Обновить категорию', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            <?php if (!$model->isNewRecord) { ?>
                <?= Html::a('Удалить категорию', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => "Удалить категорию {$model->name}?",
                        'method' => 'post',
                    ],
                ]) ?>
            <?php } ?>
        </div>
        <div class="row">
<!--            <div class="col-md-4">
                <?= $form->field($model, 'parent_id')->dropDownList(Category::getParentList(),['prompt'=>'']) ?>
            </div>
-->
            <?php if (!$model->isNewRecord) { ?>
                <div class="col-md-3">
                    <?= $form->field($model, 'updated')->textInput(['readonly' => true]) ?>
                </div>
                <div class="col-md-3">
                    <?= $form->field($model, 'created')->textInput(['readonly' => true]) ?>
                </div>
            <?php } ?>
            <div class="col-md-10">
                <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>
            </div>
            <?php if (!$model->isNewRecord) { ?>
                <div class="col-md-2">
                    <label class="control-label" for="category-active"></label>
                    <?= $form->field($model, 'active')->checkbox() ?>
                </div>
            <?php } ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</script>

basic/modules/admin/views/category/_label.php
<?php

use \app\models\Label;
use yii\widgets\ActiveForm;

$label = new Label();
?>



<div id="category-labels"></div>

<script type="text/template" id="category-labels-template">
    <div class="col-md-12">
        <h4>Введите имя новой метки или выберете из уже существующих в выподающем списке.</h4>
    </div>
    <?php $form = ActiveForm::begin([
        'action' => 'add'
    ]); ?>
    <div class="col-md-10">
        <?= $form->field($label, 'name', ['template' => "{input}"])->textInput(['placeholder' => 'Введите название метки',]) ?>
    </div>
    <div class="col-md-2">
        <a class="btn btn-sm btn-success" href="javascript:void(0)" id="save-label"><span class="glyphicon glyphicon-floppy-disk"></span></a>
    </div>
    <?php ActiveForm::end(); ?>
    <div id="labels-table"></div>
</script>

<script type="text/template" id="label-form-template">
    <?php $form = ActiveForm::begin([
        'action' => 'add'
    ]); ?>
    <input type="hidden" id="label-id" class="form-control" name="Label[id]" value="<%= id %>">
    <div style="margin-bottom: 10px; margin-top: 10px;">
        <div class="col-md-9">
            <div class="form-group field-label-name required has-success">
                <input type="text" id="label-name" class="form-control" name="Label[name]" value="<%= name %>" placeholder="Введите название метки">
            </div>
        </div>
        <div class="col-md-3">
            <a class="btn btn-sm btn-success" href="javascript:void(0)" id="save-label"><span class="glyphicon glyphicon-floppy-disk"></span></a>
            <a class="btn btn-sm btn-danger" href="javascript:void(0)" id="drop-label"><span class="glyphicon glyphicon-trash"></span></a>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</script>

<?php $this->registerJsFile('js/app/views/admin/category/labels.js', ['depends' => ['app\modules\admin\AppAsset',]]); ?>

basic/modules/admin/views/category/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\CategoryTypeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="category-search well bs-component">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>
    <div class="row">
            <div class="col-sm-2">
                <?= $form->field($model, 'id') ?>
            </div>
<!--            <div class="col-sm-5">
                <?= $form->field($model, 'parent_id')->dropDownList(\app\models\Category::getParentList(),['prompt'=>'']) ?>
            </div>
-->

            <div class="col-sm-5">
                <?= $form->field($model, 'name') ?>
            </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Подобрать', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Сбросить фильтр', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

basic/modules/admin/views/category/_value.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/** @var $value app\models\Value */

$this->registerJsFile('@web/js/main.js');

?>

<?php $form = ActiveForm::begin([
    'action' => $value->isNewRecord ?Url::toRoute(['/admin/value/save']) : Url::toRoute(['/admin/value/update', 'categoryId' => $value->id]),
]); ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($value, 'value') ?>
        </div>
        <?php if (!$value->isNewRecord)  {?>
            <div class="col-md-1">
                <?= Html::a("<span class='glyphicon glyphicon-save'></span>",['class' => 'btn btn-primary']) ?>
            </div>
        <?php } else { ?>
            <div class="col-md-1">
                <?= Html::a("<span class='glyphicon glyphicon-floppy-disk'></span>",[
                    'class' => 'btn btn-primary',
                    'onclick' => 'addValue()',
                ]) ?>
            </div>
        <?php } ?>
    </div>
<?php ActiveForm::end(); ?>

basic/modules/admin/views/category/create.php
<?php

use yii\helpers\Html;
use \yii\bootstrap\Tabs;


/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = 'Добавление категории';
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div id="category-form"></div>

<?= $this->render('_form', [
    'model' => $model,
]) ?>

<?php $this->registerJsFile('js/app/controllers/admin/category/create.js', ['depends' => ['app\modules\admin\AppAsset',]]); ?>

basic/modules/admin/views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use \yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\CategoryTypeSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Категории';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-index">

    <?php echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить категорию', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'options' => [
            'class' => 'danger',
        ],
        'columns' => [
            'id',
            [
                'attribute' => 'name',
                'format' => 'html',
                'value' => function ($model) {
                    return Html::a($model->name, Url::toRoute(['update', 'id' => $model->id]));
                }
            ],
            [
                'attribute' => 'active',
                'format' => 'html',
                'value' => function ($model) {
                    return !empty($model->active) ? '<span class="glyphicon glyphicon-ok"></span>': '<span class="glyphicon glyphicon-remove"></span>';
                }
            ],
            [
                'attribute' => 'updated',
                'format' => 'html',
                'options' => [
                    'class' => 'col-md-2',
                ],
                'value' => function ($model) {
                    return $model->updated;
                }
            ],
            [
                'attribute' => 'created',
                'format' => 'html',
                'options' => [
                    'class' => 'col-md-2',
                ],
                'value' => function ($model) {
                    return $model->created;
                }
            ],
        ],
    ]); ?>

</div>

basic/modules/admin/views/category/update.php
<?php

use \yii\bootstrap\Tabs;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Категории', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$items = [
    [
        'label' => 'Поля',
        'content' => $this->render('_field', ['model' => $model]),
        'active' => true
    ],
    [
        'label' => 'Метки',
        'content' => $this->render('_label',[
            'model' => $model,
        ]),
    ]
];

$this->registerJsFile('js/app/models/CategoryField.js', ['depends' => ['app\assets\AppAsset',]]);
$this->registerJsFile('js/app/collections/CategoryFields.js', ['depends' => ['app\assets\AppAsset',]]);
$this->registerJsFile('js/app/models/CategoryLabel.js', ['depends' => ['app\assets\AppAsset',]]);
$this->registerJsFile('js/app/collections/CategoryLabels.js', ['depends' => ['app\assets\AppAsset',]]);
?>
<div id="category-form"></div>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
<?= Tabs::widget(['items' => $items]); ?>


<?php
$fieldsToJs = [];
$labelsToJs = [];
$allLabelsToJs = [];

foreach ($model->labels as $label) {
    $labelsToJs[] = "{
        name: '{$label->name}',
        id: '{$label->id}'
    }";
}

foreach ($model->fields as $field) {
    $fieldsToJs[] = "{
        name: '{$field->name}',
        id: '{$field->id}',
        required: '{$field->required}',
        dictionary: '{$field->dictionary}',
        about: '{$field->about}',
        type_id: '{$field->type_id}',
        preview: '{$field->preview}',
    }";
}

$this->registerJs(
    "data_fields = [".join(',',$fieldsToJs)."]; category_id = {$model->id};"
    ."autocomplete_labels = ['".join("','",\app\models\Label::getLabelsWithoutThis($model->id))."'];"
    ."data_labels = [".join(',',$labelsToJs)."];",
    yii\web\View::POS_BEGIN);
?>
<?php $this->registerJsFile('js/app/controllers/admin/category/update.js', ['depends' => ['app\modules\admin\AppAsset',]]); ?>