basic/controllers/GoodController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Good;
use app\modules\admin\models\GoodSearch;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class GoodController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays a single Good model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * @param int $page
     * @param null $category_id
     * @return string
     */
    public function actionSearch($page = 1, $category_id = null)
    {
        $limit = 9;
        $searchModel = new GoodSearch();
        $count = $searchModel->search(Yii::$app->request->queryParams, $category_id)->query->limit($limit)->offset($limit* ($page - 1))->count();
        $countPage = ceil($count / $limit);
        $models = $searchModel->search(Yii::$app->request->queryParams, $category_id)->query->limit($limit)->offset($limit* ($page - 1))->all();

        $category = $category_id ? Category::findOne($category_id) : null;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'models' => $models,
            'countPage' => $countPage,
            'page' => $page,
            'category' => $category
        ]);
    }

    /**
     * Finds the Good model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Good the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Good::findOneByClient(['good.id' => $id], ['values', 'values.field', 'category', 'image'])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

basic/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Good;
use app\models\LoginForm;
use app\models\RegForm;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Html;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\User;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $goods = Good::findAllByClient([], ['values', 'values.field', 'category', 'image'], 6);

        return $this->render('index',[
            'goods' => $goods
        ]);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        return $this->render('contact');
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionReg()
    {
        $model = new RegForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($user = $model->reg(User::ROLE_ADMIN)) {
                if ($user->status == User::STATUS_ACTIVE) {
                    if (Yii::$app->getUser()->login($user)) {
                        return $this->goHome();
                    }
                }
            } else {
                Yii::$app->session->setFlash('error', "Возникла ошибка при регистрации.");
                error("Ошибка при регистрации.");
                return $this->refresh();
            }
        }

        return $this->render('reg', ['model' => $model]);
    }
}

basic/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

$this->title = 'Главная';

limion\bootstraplightbox\BootstrapMediaLightboxAsset::register($this);
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="main-body-site ">

<?php $this->beginBody() ?>

    <div class="wrap">
        <div class="nav-border">
            <?php
            NavBar::begin([
                'brandLabel' => 'Антиквариат',
                'brandUrl' => '/',
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);

            echo Nav::widget([
                'options' => ['class' => 'navbar-nav'],
                'items' => [
                    ['label' => 'Каталог', 'url' => ['/good/search']],
                    ['label' => 'Контакты', 'url' => ['/site/contact']],
                    ['label' => 'О нас', 'url' => ['/site/about']],
                ],
            ]);

            $userMenu = [];
            if (Yii::$app->user->isGuest) {
                $userMenu = [
                    ['label' => 'Войти', 'url' => ['/site/login']],
                    ['label' => 'Зарегистрироваться', 'url' => ['/site/reg']],
                ];
            } else {
                $userMenu = [
                    ['label' => 'Выйти (' . Yii::$app->user->identity->username . ')',
                        'url' => ['/site/logout'],
                        'linkOptions' => ['data-method' => 'post']],
                ];
            }

            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $userMenu,
            ]);
            NavBar::end();
            ?>
        </div>
        <div class="container" >
            <div class="row row-centered" style="border: 2px solid #333333">
                <div class="col-md-2 category-bar" style="border: 2px solid #333333">
                    <ul class="nav nav-pills nav-stacked" style="max-width: 260px;">
                        <legend>Категории</legend>
                        <?php foreach (\app\models\Category::find()
                                           ->select(['category.id as id', 'category.name as name'])
                                           ->joinWith(['goods'])
                                           ->groupBy(['category.id'])->all() as $row) {

                            ?>
                            <li class="">
                                <a href="<?= \yii\helpers\Url::toRoute(["good/search", 'page' => 1, "category_id" => $row['id']]) ?>">
                                    <span class="badge pull-right"><?= '' ?></span>
                                    <?= $row['name'] ?>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
                <div class="col-md-9 content-container" style="border: 2px solid #333333">
                    <?php Breadcrumbs::widget([
                        'homeLink' => [
                            'label' => Yii::t('yii', 'Админка'),
                            'url' => '/admin',
                        ],
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    ]) ?>
                    <?= $content ?>
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
    </div>

    <div class="container">
    </div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>